In [98]:
import numpy as np

In [99]:
p = (np.arange(0,1+0.1,0.1))
p

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [100]:
sum(p[1:10])

4.500000000000001

In [196]:
 def integrate(f, a, b, n):
    h = ((b-a)/n)
    arrayx = np.arange(a, b+h, h)
    lstx = list(arrayx)
    return h/2(lstfx[0] + 2*(sum(lstfx[1:10]) + lstfx[10]))
    

In [197]:
integrate(x**2,0,1,10)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [195]:
f = x**2
a = 0
b = 1
n = 10

In [183]:
h = ((b-a)/n)
h

0.1

In [184]:
arrayx = np.arange(a, b+h, h)
lstx = list(arrayx)
lstx

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [185]:
lstfx = [f for x in lstx]
lstfx

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [186]:
lstx[0]

0.0

In [187]:
for i in lstx:
    print(i)

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9
1.0


In [188]:
lstfx = [] 
for i in lstx:
    lstfx.append[i]
    
h/2(lstfx[0] + 2*(sum(lstfx[1:10]) + lstfx[10]))

TypeError: 'builtin_function_or_method' object is not subscriptable

In [189]:
lstx

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [190]:
for i in lstx:
    print(i)

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9
1.0


In [191]:
lst = []
for x in lstx:
    lst.append(f)

In [192]:
lst

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [310]:
def integrate(f, a, b, n):
    np.linspace(a, b, n)
    array_x = np.arange(a, b+h, h)
    array_fx = np.array([x**2 for x in array_x])
    print(int(b/h))
    return (h/2)*(array_fx[0] + 2*(sum(array_fx[int(b/h)])) + array_fx[10])

In [ ]:
def integrate(f, a, b, n):
    array_x = np.linspace(a, b, n)
    

In [396]:
def integrar(f, a, b, n):
    x = np.linspace(a, b, n)
    fx = f(x)
    area = np.sum(fx)*(b-a)/n
    return area

In [397]:
integrar(np.sin, 0, np.pi/2, 100)

0.9978332121772983

In [398]:
def integrate(f, a, b, n):
    x = np.linspace(a+(b-a)/(2*n), b-(b-a)/(2*n), n)
    fx = f(x)
    area = np.sum(fx)*(b-a)/n
    return area

In [399]:
integrate(np.sin, 0, np.pi/2, 100)

1.0000102809119051

In [361]:
def exp(x):
    return x**2

In [369]:
y = np.linspace(2, 5, 10)

exp(y)

array([ 4.        ,  5.44444444,  7.11111111,  9.        , 11.11111111,
       13.44444444, 16.        , 18.77777778, 21.77777778, 25.        ])

In [370]:
type(p)

numpy.ndarray

In [371]:
p = np.ndarray([1,2,3,4,5,6])
print(p)

[[[[[[8.18422510e-312 8.18559363e-312 0.00000000e+000 0.00000000e+000
      9.85330308e+165 1.50008929e+248]
     [1.67751549e+243 2.51313500e+180 3.48869709e-143 6.19941898e-071
      4.47593874e-091 4.47593816e-091]
     [4.47593816e-091 4.47593816e-091 4.47593816e-091 4.47593816e-091
      4.47593816e-091 4.47593816e-091]
     [4.47593816e-091 1.06032943e+136 9.02193423e+217 9.16281386e-072
      2.14247177e+108 6.99177865e+228]
     [1.61410559e+132 6.01347002e-154 6.01347002e-154 6.01347002e-154
      6.01347002e-154 9.85330622e+165]]

    [[1.09865413e+248 6.96407597e+252 1.97717802e+161 2.11212619e+257
      6.61020367e-062 1.49460967e+195]
     [9.82391603e+252 4.31316273e-033 3.27297611e+179 9.89803615e+164
      5.97144951e+135 1.35301660e-023]
     [3.06836125e+257 9.16281386e-072 1.69812242e+137 9.02193423e+217
      9.89803615e+164 4.51430221e-091]
     [2.95151418e-075 4.67485108e-062 9.89803615e+164 1.19490107e+190
      9.16281387e-072 1.42137876e-076]
     [1.05901196e

In [364]:
integrar(exp, 0, 1, 1000000)

(0.33333350000016665,
 array([0.000000e+00, 1.000002e-12, 4.000008e-12, ..., 9.999960e-01,
        9.999980e-01, 1.000000e+00]))

In [331]:
integrar(np.sin, 0, np.pi/2, 100)

0.9978332121772983

In [318]:
np.linspace(0, 1, 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [205]:
f = x**2
a = 0
b = 1
n = 10
h = ((b-a)/n)
return h/2(lstfx[0] + 2*(sum(lstfx[1:(b/h)])) + lstfx[10])

In [206]:
array_x = np.arange(a, b+h, h)

In [207]:
lstx = list(array_x)

In [208]:
lstx

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [209]:
array_x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [213]:
array_fx = np.array([x**2 for x in array_x])
array_fx

array([0.  , 0.01, 0.04, 0.09, 0.16, 0.25, 0.36, 0.49, 0.64, 0.81, 1.  ])

In [301]:
np.trapz([1,2,3])


4.0

In [305]:
np.trapz([x,2,3])
np.trapz([x,2,3], x=[4,6,8])

8.0